/*
 * generated by Xtext 2.34.0
 */
package org.nadeeshaan.d3dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.nadeeshaan.d3dsl.D3DslRuntimeModule;
import org.nadeeshaan.d3dsl.D3DslStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class D3DslIdeSetup extends D3DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new D3DslRuntimeModule(), new D3DslIdeModule()));
	}
	
}
