/*
 * generated by Xtext 2.34.0
 */
package org.nadeeshaan.d3dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractD3DslScopeProvider extends DelegatingScopeProvider {
}
