/*
 * generated by Xtext 2.34.0
 */
package org.xtext.demo.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.demo.dsl.ExpLangRuntimeModule;
import org.xtext.demo.dsl.ExpLangStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ExpLangIdeSetup extends ExpLangStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ExpLangRuntimeModule(), new ExpLangIdeModule()));
	}
	
}
