/*
 * generated by Xtext 2.34.0
 */
package org.nadeeshaan.d3dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractD3DslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.nadeeshaan.d3dsl.d3Dsl.D3DslPackage.eINSTANCE);
		return result;
	}
}
