/*
 * generated by Xtext 2.34.0
 */
package org.xtext.demo.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExpLangStandaloneSetup extends ExpLangStandaloneSetupGenerated {

	public static void doSetup() {
		new ExpLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
