/*
 * generated by Xtext 2.34.0
 */
package org.nadeeshaan.d3dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.nadeeshaan.d3dsl.parser.antlr.internal.InternalD3DslParser;
import org.nadeeshaan.d3dsl.services.D3DslGrammarAccess;

public class D3DslParser extends AbstractAntlrParser {

	@Inject
	private D3DslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalD3DslParser createParser(XtextTokenStream stream) {
		return new InternalD3DslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public D3DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(D3DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
