/*
 * generated by Xtext 2.34.0
 */
package org.xtext.demo.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.demo.dsl.parser.antlr.internal.InternalExpLangParser;
import org.xtext.demo.dsl.services.ExpLangGrammarAccess;

public class ExpLangParser extends AbstractAntlrParser {

	@Inject
	private ExpLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExpLangParser createParser(XtextTokenStream stream) {
		return new InternalExpLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ExpLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExpLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
