/*
 * generated by Xtext 2.34.0
 */
package org.xtext.demo.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExpLangScopeProvider extends DelegatingScopeProvider {
}
