/*
 * generated by Xtext 2.34.0
 */
package org.nadeeshaan.d3dsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class D3DslScopeProvider extends AbstractD3DslScopeProvider {

}
