/*
 * generated by Xtext 2.34.0
 */
package org.nadeeshaan.d3dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class D3DslStandaloneSetup extends D3DslStandaloneSetupGenerated {

	public static void doSetup() {
		new D3DslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
