/*
 * generated by Xtext 2.34.0
 */
package org.nadeeshaan.d3dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class D3DslRuntimeModule extends AbstractD3DslRuntimeModule {
}
